name: Daily Request with WeChat Notify

on:
  schedule:
    - cron: '0 9 * * *'  # 北京时间下午5点
  workflow_dispatch:

jobs:
  request-and-notify:
    runs-on: ubuntu-latest
    environment: test  # 添加这行，指定环境名称
    steps:
      - name: Send Request
        id: request
        run: |
          RESPONSE=$(curl -s -X POST "https://ezapi.z-dragon.cc/a3f9c2e8/7d4b91af/eFFwVkMwWUZEMnZjdy82MEpCZUNEQT09" \
            -H "authorization: ${{ secrets.AUTHORIZATION }}" \
            -H "x-iv: ${{ secrets.X_IV }}" \
            -H "content-type: application/x-www-form-urlencoded" \
            -H "user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Safari/537.36" \
            --data-urlencode "type=2" \
            --data-urlencode "input=1GB")
              # 使用 python 将 Unicode 编码转为中文
          RESPONSE=$(echo "$RESPONSE" | python3 -c "import sys, json; print(json.dumps(json.load(sys.stdin), ensure_ascii=False, indent=2))")
          
          echo "response=$RESPONSE" >>$GITHUB_OUTPUT
      
      - name: Print Response
        run: |
          echo "===== 请求结果 ====="
          echo "${{ steps.request.outputs.response }}"
          echo "===================="
      
      - name: Notify WeChat
        if: always()
        env:
          SERVERCHAN_KEY: ${{ secrets.SERVERCHAN_KEY }}
        run: |
          if [[ "$SERVERCHAN_KEY" =~ ^sctp([0-9]+)t ]]; then
            num=${BASH_REMATCH[1]}
            url="https://${num}.push.ft07.com/send/${SERVERCHAN_KEY}.send"
          else
            url="https://sctapi.ftqq.com/${SERVERCHAN_KEY}.send"
          fi
          
          curl -v -X POST "$url" \
            -H "Content-type: application/x-www-form-urlencoded" \
            --data-urlencode "text=每日签到结果" \
            --data-urlencode "desp=请求结果：${{ steps.request.outputs.response }}"
